project:
  type: website

website:
  title: "Vinita Vader"
  
  favicon: "images/picture_vader.jpeg"
  
  page-footer:
    center: |
      [Contact Vinita Vader](mailto:vinitavader@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/vvader24)
    background: "#266867"
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Posts
        href: posts.qmd
      - text: Resume
        href: cv/Vader_resume.html
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vvader24
      - icon: twitter
        href: https://twitter.com/v_vader_
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

